### ISSUE TITLE
Panic in RtcServer

### ISSUE THREAD

**Issue by smokku** [naia-rs/naia-socket#17]
When I try running a new server instance when one is already running on the same port, the process crashes.

    thread 'Compute Task Pool (3)' panicked at 'could not start RTC server: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', /home/smoku/.cargo/registry/src/github.com-1ecc6299db9ec823/naia-server-socket-0.4.0/src/webrtc_server_socket/mod.rs:149:14

I would like to handle this error in my server - log an error message and shutdown process cleanly.

**Comment by johnpmayer** [comment]
This feels like a bug in https://github.com/naia-rs/naia-socket/blob/master/server/src/impls/webrtc/server_socket.rs#L134
