### ISSUE TITLE
Client won't connect in Safari

### ISSUE THREAD

**Issue by ostwilkens** [naia-rs/naia-socket#42]
The demo works great in Chrome, but in Safari it doesn't want to connect. 
Running MacOS 11.4 and Safari 14.1.1. 

The error output in the console is: 
`Failed to load resource: Cancelled load from 'http://127.0.0.1:14191/new_rtc_session' because it is using HTTP/0.9.`

**Comment by naia-rs** [comment]
Hey sorry I've taken so long to respond, but I definitely will be checking this bug out soon after the next release. Thank you very much for reporting it!

**Comment by ostwilkens** [comment]
PR: https://github.com/naia-rs/naia-socket/pull/52

**Comment by naia-rs** [comment]
Released with https://github.com/naia-rs/naia-socket/releases/tag/v0.7.4, thank you so much!
