### ISSUE TITLE
wasm server sockets

### ISSUE THREAD

**Issue by johanhelsing** [naia-rs/naia-socket#45]
Hi,

I was wondering if establishing peer-to-peer WebRTC connections (with the help of a signalling server) was within scope for naia-socket?

@ErnWong's [patched version of naia-socket](https://github.com/ErnWong/dango-tribute/tree/master/patches/naia-socket) implements `ServerSocketTrait` for wasm_bindgen and uses a signalling server to set up client-server connections between two or more browsers.

Presumably the same approach could be used to enable p2p networking in the browser, which would make naia-socket very attractive for crates like ggrs.

**Comment by naia-rs** [comment]
Hi @johanhelsing ! Sorry for not getting back to your earlier. Thanks for bringing ErnWong's implementation to my attention, that was very interesting, and while I was aware of his work, I didn't know he was using naia-socket for any of it. :+1: 

From the beginning with the Naia project, I have definitely felt that some kind of `naia-peer-socket` crate would be ideal (I don't think it'd be a good idea to try to force the client/server implementations into the P2P paradigm). Currently it'd probably be the case that such a socket would need to either be UDP <-> UDP only (on native), or WebRTC <-> WebRTC only (on browsers). HOWEVER, once something like https://github.com/webrtc-rs/webrtc is finished, we'd be able to have some true WebRTC <-> WebRTC P2P sockets that can work across the native/browser divide ... that'd be pretty awesome!

Anyway, it's not likely something that I'm going to work on in the immediate future, but I'd like to get to it eventually!

BTW @johanhelsing .. https://github.com/johanhelsing/matchbox looks freaking awesome, way to go on getting that out there! :muscle: I am tempted to set up some quick and dirty `naia-peer-socket` crate in this repo that just wraps `matchbox-socket` for the Wasm implementation ;) I'm wondering if you have any plans to get `matchbox-socket` able to cross-compile to work on native via UDP? Might be useful for testing/debugging at the least.

**Comment by johanhelsing** [comment]
Thanks for the kind words! :) And yeah, I think having something that cross-compiles and works p2p on both native and web would be awesome, wherever it ends up :)

For what it's worth, there currently is a thin wrapper in `matchbox_socket` that implements GGRS' `NonBlockingSocket` trait, which is also implemented for for UDP in ggrs itself. Which means with some ifdefs at the beginning, you could cross-compile the same application on both native and WebRTC. That said, there were some challenges with this.

The `NonBlockingSocket` trait assumes you know the `SocketAddr`'s of the other peers when sending/receiving messages. I don't know, maybe it's possible to extract this from WebRTC - ErnWong seemed to think it would be possible to pull it out from the SDP string. It certainly isn't something that is natural to use when dealing with WebRTC, though. For now I kind of cheated and just hashed the peer id's (string/uuids) that are used in `matchbox_socket` into a fake mapping from socketaddr to data channel.

As for implementing matchbox socket in UDP as well, I think it should be relatively doable. At least for debugging. I'm a bit reluctant to get into NAT hole-punching on UDP, but something that just works on the same network should be relatively straightforward.

That said, depending on how far away https://github.com/webrtc-rs/webrtc is, it may very well be easier to just wait for it. It'd definitely help in keeping the scope of matchbox manageable.

In any case, if you want to have a go at a `naia-peer-socket` crate please let me know if there are ways I can help! For instance if there are changes to the `matchbox_socket` api that would make it easier to use.

**Comment by naia-rs** [comment]
Hey JohanHelsing, hope you're well and matchbox progress is coming along! I've decided naia-socket should stay client/server focused for the time being, I'll definitely point people your way for a peer-to-peer solution :) Thanks again!
