### ISSUE TITLE
Potentially yank 0.7.4 and reupload as 0.8.0

### ISSUE THREAD

**Issue by elijaharita** [naia-rs/naia-socket#54]
I'm super happy the changes in 0.7.4 allow connecting via a URL string, thank you. However it had a breaking interface change. Every existing project depending on `naia-client-socket = "0.7"` and the likes will break if built with a new Cargo.lock, and the dep line would have to be replaced with `naia-client-socket = ">=0.7.0, <0.7.4"` to be able to build.

This is the first time I've encountered this kind of issue, maybe it is a common thing not to worry about? But it does not seem right to me. Just wanted to bring awareness to the issue I encountered. I think this version should potentially be yanked and reuploaded as 0.8.0, so the breaking change doesn't propagate to people's projects without them intentionally updating their Cargo.toml.

https://doc.rust-lang.org/cargo/reference/semver.html#major-addingremoving-function-parameters

**Comment by elijaharita** [comment]
On this topic - I noticed that `naia_client_socket::Socket::connect()` takes `&str`, but `naia_server_socket::Socket::listen()` takes `url::Url` via the `ServerAddrs` struct. Is there a reason behind the discrepancy?

**Comment by elijaharita** [comment]
For reference, if you have an existing Cargo.lock, the dependency will not automatically update unless you run `cargo update`. But that file doesn't get committed, so anyone building the project after newly cloning a repository will receive the latest patch/dev-minor versions from cargo, if the patch/dev-minor version isn't manually specified in Cargo.toml.

**Comment by naia-rs** [comment]
Thanks again @elijaharita ! Hope all goes well w/ your project. https://github.com/naia-rs/naia-socket/releases/tag/v0.8.0
