### ISSUE TITLE
Demo app on "use-webrtc" crashes with "Already Borrowed: BorrowMutError" when it can't connect to the server

### ISSUE THREAD

**Issue by Oberdiah** [naia-rs/naia-socket#58]
It's probably worth demonstrating how to handle this more gracefully in the demo, as it's something that all naia-socket applications will have to handle.

`panicked at 'already borrowed: BorrowMutError', naia-client-socket-0.9.0\src\impls\wasm_bindgen\packet_sender.rs:45:70`

**Comment by naia-rs** [comment]
Thanks for the heads up :+1: def will address this in the next release
